stages:
  - build

variables:
  IMAGE_NAME: tel-bot-youtube-downloader
  DOCKER_TLS_CERTDIR: ""

build:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  before_script:
    - echo ${DOCKER_REGISTRY_PASSWORD} | docker login ${DOCKER_REGISTRY_HOSTNAME} -u ${DOCKER_REGISTRY_USERNAME} --password-stdin
  script:
    - docker build --pull \
      --build-arg TELOXIDE_TOKEN \
      -t "$DOCKER_REGISTRY_HOSTNAME/$IMAGE_NAME:latest" .
    - docker push "$DOCKER_REGISTRY_HOSTNAME/$IMAGE_NAME:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

