stages:
  - build

variables:
  DOCKER_TLS_CERTDIR: ""

build:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  script:
    - echo ${DOCKER_REGISTRY}
    # - docker build --pull \
    #   --build-arg TELOXIDE_TOKEN \
    #   -t "$CI_REGISTRY_IMAGE:latest" .
    # - docker push "$CI_REGISTRY_IMAGE:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

