stages:
  - build

variables:
  DOCKER_TLS_CERTDIR: ""

build:
  image: docker:stable
  stage: build
  services:
    - docker:dind
      command: ["--insecure-registry=registry.docker.lan"]
      privileged: true
  script:
    - docker build --pull -t "$DOCKER_REGISTRY/$CI_PROJECT_NAME:latest" .
    - docker push "$DOCKER_REGISTRY/$CI_PROJECT_NAME:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

