stages:
  - build

variables:
  DOCKER_TLS_CERTDIR: ""

build:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  script:
    - docker build --pull -t "$DOCKER_REGISTRY/$CI_PROJECT_NAME:latest" .
    - docker push "$DOCKER_REGISTRY/$CI_PROJECT_NAME:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

