stages:
  - build

variables:
  DOCKER_TLS_CERTDIR: ""

build:
  image: docker:stable
  stage: build
  services:
    - docker:dind
  before_script:
    # - echo "${CI_REGISTRY_PASSWORD}" | docker login "${CI_REGISTRY}" -u "${CI_REGISTRY_USER}" --password-stdin
  script:
    - echo ${CI_REGISTRY_IMAGE}
    # - docker build --pull \
    #   --build-arg TELOXIDE_TOKEN \
    #   -t "$CI_REGISTRY_IMAGE:latest" .
    # - docker push "$CI_REGISTRY_IMAGE:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

