stages:
  - build
  - deploy
  - validate

build:
  image: docker:stable
  stage: build
  services:
    - name: docker:dind
      command: ["--insecure-registry=registry.docker.lan"]
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker build --pull -t "$DOCKER_REGISTRY/$CI_PROJECT_NAME:latest" .
    - docker push "$DOCKER_REGISTRY/$CI_PROJECT_NAME:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

deploy:
  stage: deploy
  tags: [ "shell" ]
  before_script:
    - docker context use docker-swarm
  script:
    - docker stack deploy --detach=true --compose-file=./deploy/docker-swarm/prd.yaml ${CI_PROJECT_NAME}
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

validate:
  stage: validate
  tags: [ "shell" ]
  before_script:
    - docker context use docker-swarm
  script:
    - ./deploy/bin/timeout-validate-deploy.sh ${CI_PROJECT_NAME}_bot $DOCKER_REGISTRY/$CI_PROJECT_NAME:latest 1
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
